### ISSUE TITLE
Rollershutter

### ISSUE THREAD

**Issue by Timo-Me** [fdebrus/Nikobus-HA#22] opened 2024-09-27 20:54 UTC
HI,
When using the rollershutters the timers are not correct when you use the dashboard.
They don't respect the times as defined in the nikobus module config file. When you use the sliders it works but not with the up/down buttons.

**Comment by fdebrus** [comment] 2024-09-27 21:08
Hi,

So using this fails

![image](https://github.com/user-attachments/assets/9a70b1b6-491e-482a-8d64-f30361c0a8a8)

This work 

![image](https://github.com/user-attachments/assets/927e860b-cf83-4f69-b7d9-95334741e631)


Could you be more specific as I do not have this issue, does it stops too early when opening / closing, after a set position then a full open, a full close, etc...

thanks !

**Comment by Timo-Me** [comment] 2024-09-29 12:11
HI,
I did restart the system twice and i can't reproduce the problem.
You can close this issue.

**Comment by Timo-Me** [comment] 2024-09-29 12:11
Thanks for the support - looks good!

**Comment by fdebrus** [comment] 2024-09-29 16:17
Could not reproduce

**Closed by fdebrus** 2024-09-29 16:17 UTC
